# Generated by Django 6.1.1 on 2026-09-04 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('ADMINISTRATIVE', 'Administrative'), ('CAREER', 'Career'), ('FINANCIAL', 'Financial'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('instructions', models.TextField(blank=True, help_text='Instructions shown to applicants.')),
                ('requirements', models.TextField(blank=True, help_text='Requirements shown to applicants.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationEligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('ROLE', 'Role'), ('DEPARTMENT', 'Department'), ('PROGRAM', 'Program'), ('YEAR', 'Year'), ('SEMESTER', 'Semester'), ('BATCH', 'Batch')], max_length=30)),
                ('operator', models.CharField(choices=[('EQUALS', 'Equals'), ('NOT_EQUALS', 'Not Equals'), ('IN', 'Is One Of'), ('NOT_IN', 'Is Not One Of')], default='EQUALS', max_length=20)),
                ('value', models.CharField(help_text='For IN/NOT IN, enter comma-separated values.', max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='workflows.application')),
            ],
            options={
                'ordering': ['field'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='workflows.application')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(blank=True, default=dict, help_text='Submitted application form data.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_requests', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='workflow_requests/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workflows.workflowrequest')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the review stage.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('assigned_role', models.CharField(choices=[('FACULTY', 'Faculty'), ('HOD', 'Head of Department'), ('HOS', 'Head of School'), ('ADMIN', 'Administrator')], max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_requests', to='workflows.workflowstep'),
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REQUEST_CHANGES', 'Request Changes'), ('COMMENT', 'Comment'), ('CANCEL', 'Cancel')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_actions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.workflowrequest')),
                ('from_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions_from', to='workflows.workflowstep')),
                ('to_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions_to', to='workflows.workflowstep')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable business action.', max_length=150)),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REQUEST_CHANGES', 'Request Changes')], max_length=30)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflows.workflowstep')),
                ('target_step', models.ForeignKey(blank=True, help_text='Leave empty when this action ends the workflow or returns the request to the applicant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflows.workflowstep')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal field name. Example: course_code', max_length=100)),
                ('label', models.CharField(help_text='Label shown to the applicant.', max_length=200)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'Long Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('URL', 'URL'), ('SELECT', 'Dropdown'), ('FILE', 'File Upload'), ('CHECKBOX', 'Checkbox')], default='TEXT', max_length=20)),
                ('help_text', models.CharField(blank=True, help_text='Optional explanation shown below the field.', max_length=500)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(blank=True, default=list, help_text='For dropdowns. Example: ["Option 1", "Option 2", "Option 3"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='workflows.application')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('application', 'name'), name='unique_application_field_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.UniqueConstraint(fields=('workflow', 'order'), name='unique_step_order_per_workflow'),
        ),
    ]
