# Generated by Django 6.1.1 on 2026-09-04 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_workflowrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrequest',
            name='return_step',
            field=models.ForeignKey(blank=True, help_text='Review stage to return to when the applicant resubmits after changes are requested.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_requests', to='workflows.workflowstep'),
        ),
    ]
